### ISSUE TITLE
URL templating not complete

### ISSUE THREAD

**Issue by stefanpenner** [kurko/ember-json-api#15]
url templating is only aware of the current model's ID, but to be compatible actually needs reference to the entire model.

This may need some ember-data level adjustments, but well worth it.

example:

```json
{
  "links": {
    "posts.comments": "http://example.com/comments/{posts.comments}"
  }
}
```

the built url, incorrectly templates `{posts.comments}` with the primary models id.

http://jsonapi.org/format/#document-url-template-shorthands elaborates other variations.

(cc @rjackson you mentioned similar ideas earlier today)

**Comment by jonkoops** [comment]
@stefanpenner @wecc I assume work for this has been done in the official Ember Data adapter?

**Comment by igorT** [comment]
This can be closed as this is no longer in JSONAPI

**Comment by kurko** [comment]
@jonkoops closing. I think we'll deprecate the lib before this issue ever has a chance to be fixed.

**Comment by jonkoops** [comment]
@kurko Definitely, just making sure this isn't anything that should be implemented in the official.
