### ISSUE TITLE
Use PATCH instead of PUT for updating records

### ISSUE THREAD

**Issue by daliwali** [kurko/ember-json-api#3]
Currently, the adapter still follows the default REST adapter behaviour when updating records, which is to PUT the entire resource. A smarter, better approach would be to only serialize changes, and send the request as a PATCH. 

The request might look something like this:
```
PATCH /animals/123
Content-Type: application/json-patch+json

[
  {"op": "replace", "path": "/animals/0/name", "value": "Tomster"},
  {"op": "replace", "path": "/animals/0/links/friends", "value": ["124"]}
]
```

**Comment by andrewbranch** [comment]
Looks like PUT is no longer mentioned in the spec. What’s the status of this?

**Comment by jonkoops** [comment]
I've found some additional information about PUT requests in the [FAQ](http://jsonapi.org/faq/#wheres-put):

> ## Where's PUT? Can I use method X to do Y?

> JSON API does not currently specify the use of the PUT method for any purpose.

> Servers may complement the base specification by providing extra capabilities and alternative ways of requesting certain operations (e.g., resource creation via PUT in addition to POST).

**Comment by andrewbranch** [comment]
So shouldn’t this change be incorporated into #71? I can look into it if it’s not already in progress elsewhere.

**Comment by kurko** [comment]
Yes, I think it should @andrewbranch.

**Comment by andrewbranch** [comment]
@kurko Already done :)

**Comment by jonkoops** [comment]
Closing this issue since the discussed code has been merged into master.
