### ISSUE TITLE
Underscored or hyphenated urls?

### ISSUE THREAD

**Issue by johanneswuerbach** [kurko/ember-json-api#53]
I couldn't find any hint in http://jsonapi.org/, but how should URLs for models like `PlaceRequest` look like? `api/place_requests` (ED uses this today) or `api/place-requests` (Everything is hyphenated in ember-cli)

//cc @stefanpenner

**Comment by jamonholmgren** [comment]
@johanneswuerbach , did you end up getting clarity on this?

**Comment by jamonholmgren** [comment]
Okay, so it looks like the jsonapi spec recommends dasherized URLs, meaning this adapter isn't conforming to that:

> It is also recommended that resource types be pluralized. Dasherized and pluralized resource types can be used as URL segments without translation

I can work on a pull request if @kurko agrees this should happen.

**Comment by aceofspades** [comment]
:+1:

**Comment by jonkoops** [comment]
@jamonholmgren No need for that, work is being done the pull request for RC3 compliance to dashterize all the things. See https://github.com//ember-json-api/issues/8#issuecomment-97548478.

**Comment by jamonholmgren** [comment]
Oh, nice. Thanks @jonkoops !

**Comment by jonkoops** [comment]
Closing this issue because @eneuhauser's work on this has been merged.
