### ISSUE TITLE
Publishing latest version to Bower

### ISSUE THREAD

**Issue by muchweb** [kurko/ember-json-api#55]
1. Bower's published package links to [@JacksonGariety's (outdated) fork](https://github.com/JacksonGariety/ember-json-api), not this repo

2. If package name wouldn't be available on Bower, to add corect `README` installation instructions

This also relates to #38

**Comment by jonkoops** [comment]
@JacksonGariety Would it be possible for you to [unregister your Bower package](http://bower.io/docs/creating-packages/#unregister) so we can register this repository as the official one?

**Comment by JacksonGariety** [comment]
@jonkoops done

**Comment by jonkoops** [comment]
Thank you @JacksonGariety. I've moved ownership of the bower package to this repository. @muchweb would it be possible for you to verify that the installation is working correctly?

**Comment by kurko** [comment]
Finally! :heart:

**Comment by jonkoops** [comment]
v0.5 has been [released](https://github.com/kurko/ember-json-api/releases/tag/0.5.0) by @kurko, so I am closing this issue. I am also closing associated Bower issue #38. If any further issues are present create a new issue and they will be addressed.

**Comment by muchweb** [comment]
:+1:

**Comment by kurko** [comment]
:+1:
