### ISSUE TITLE
Using in browser

### ISSUE THREAD

**Issue by muchweb** [kurko/ember-json-api#56]
1. In `README`, it needs to be made more clear that this is intended to be used with `ember-cli`.
2. To to release browserified drop-in version that could be easily included in HTML.

**Comment by meismann** [comment]
When I include `ember-json-api/dist/ember-json-api.js` in my browser app, I get an error:
```
TypeError: DS.JsonApiSerializer is undefined
```
I have already included `loader.js/loader`, so the define statement in the dist-file gets understood. Can somebody please update the installation instructions for browser apps?

**Comment by jonkoops** [comment]
I've registered the bower package to this repository, it is highly advised to use Ember CLI going forward. I'm closing this issue. If any issues still arise please open a new issue and it will be addressed.
