### ISSUE TITLE
Request: track ember-data version numbers

### ISSUE THREAD

**Issue by aceofspades** [kurko/ember-json-api#66]
The beta-15 breaking changes may delay some apps from upgrading. I'm disappointed with the lack of [semantic versioning of ember data](http://discuss.emberjs.com/t/ember-data-semantic-versioning/7354) but it does perhaps call for tracking to ember-data versions here.

Ugly, but perhaps branches `1.0.0-beta.14-v0.2.3` and `1.0.0-beta.15-v0.3.0` might be good names until data hits 1.0. Basically I may need to stick with beta.14 for now.

Thoughts?

**Comment by kurko** [comment]
That's a good idea, @aceofspades. I'll create them when I release later, although some versions will only accept one version or the other.

**Comment by jonkoops** [comment]
I wouldn't consider the way Ember data has released versions counter to semantic versioning as it hasn't hit a true 1.0 yet (though it is a bitch). With the promise of a stable version of Ember data together with the release of Ember 2.0 I don't think we should need to track Ember data versions in the near future. In the meanwhile I do think it would be a good idea to add the required version of Ember data in the release notes.

**Comment by jonkoops** [comment]
I think this issue is no longer relevant with the upcoming release of Ember Data and it's built-in JSON API Adapter. Therefore I am closing this issue.

**Comment by kurko** [comment]
:+1:
