### ISSUE TITLE
Set headers automatically?

### ISSUE THREAD

**Issue by joachimhs** [kurko/ember-json-api#69]
Hello, 

Is there a specific reason why the adapter does not set these two JSON Api Specific headers automatically? 

Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

I was wondering if there is a specific reason before I submit a PR :)

**Comment by jonkoops** [comment]
@joachimhs This functionality is added in a [pull request](https://github.com/kurko/ember-json-api/pull/71) that will make this package compliant with the RC3 version of the specification.

**Comment by jonkoops** [comment]
@kurko This functionality was introduced in #71, can you close this issue?

**Comment by jonkoops** [comment]
Closing this issue because the functionality was introduced in #71 which has been merged with master.
