### ISSUE TITLE
Update Links Property href to resource

### ISSUE THREAD

**Issue by wwwdata** [kurko/ember-json-api#70]
In the latest jsonapi.org Standard, the url to fetch related records was renamed to `resource`, see http://jsonapi.org/format/#document-structure-resource-relationships

**Comment by jonkoops** [comment]
@wwwdata Progress on RC3 compliance can be found in [this pull request] (https://github.com/kurko/ember-json-api/pull/71). Please add your comment there if the issue persists in the latest version of the pull request.

**Comment by wwwdata** [comment]
yes, this issue is old, i will close it
