### ISSUE TITLE
Warning: package `ember-json-api` is not a properly formatted package

### ISSUE THREAD

**Issue by spundun** [kurko/ember-json-api#74]
```
test_frontend$ ember install:addon ember-json-api
version: 0.2.1
Installed packages for tooling via npm.
The package `ember-json-api` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/<snip>/test_frontend/node_modules/ember-json-api`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
Installed addon package.
```

**Comment by spundun** [comment]
Scroll the pasted message to the right to see the relevant part of the warning.

**Comment by jonkoops** [comment]
@spundun Seems the path to the `main` entry in package.json is malformed. I'll whip up a pull request to fix it.

**Comment by spundun** [comment]
Great! I'm glad I could help. :+1:

**Comment by joeyespo** [comment]
Came here to report the same thing. Happy to see it's already PR'd :+1:

**Comment by dopudesign** [comment]
same here! :+1:

**Comment by MarkLunney** [comment]
I'm getting this issue too, will this be pushed to master so we don't need to point to the patch-2 branch?

**Comment by jonkoops** [comment]
@MarkLunney The pull request merges directly into the master of this repo. But I think @kurko is a but too busy at RailsConf right now.

**Comment by wvteijlingen** [comment]
:+1: seems like an easy merge to solve this annoying error :).

**Comment by jonkoops** [comment]
Closing this issue because the related pull request has been merged into master. If anyone still encounters any issues I'll reopen it.
