### ISSUE TITLE
Need to replace "data" with key for type?

### ISSUE THREAD

**Issue by andrewbranch** [kurko/ember-json-api#75]
Maybe I'm just doing something wrong, but this package isn't working for me. My very simple server response looks like

```json
{"links":{"self":"http://localhost:8080/api/bulletins"},"data":[]}
```

and Ember fails while warning me `Encountered "data" in payload, but no model was found for model name "datum"`.

If, during, the serialization, I do

```javascript
payload.bulletins = payload.data;
delete payload.data;
```

it works. Am I missing something, or are you?

**Comment by jonkoops** [comment]
@andrewbranch It looks like the response of your API conforms to the RC3 version of the specification, but the latest version of ember-json-api still only supports RC1. If you want to try out a version that supports RC3 of the specification please [use this pull request](https://github.com/kurko/ember-json-api/pull/71). Note that the pull request is very much a WIP if you find any issues please report them there.

**Comment by andrewbranch** [comment]
Awesome, thanks for pointing me in the right direction! I'm happy to try the PR and contribute to moving it forward wherever I can.
