### ISSUE TITLE
Adapter.findHasMany error on snapshot.hasMany(relationship.key)

### ISSUE THREAD

**Issue by green-arrow** [kurko/ember-json-api#83]
In the `findHasMany` function, the relationship is being queried in the first line:

```javascript
var hasManyLoaded = snapshot.hasMany(relationship.key).filter(function(item) { return !item.record.get('currentState.isEmpty'); });
```

However, it looks like now the result of `snapshot.hasMany(relationship.key)` is coming back as undefined instead of an empty array, which I believe was the original result when I first wrote that line.

Changing to something like the following should resolve the issue:

```javascript
var hasMany = snapshot.hasMany(relationship.key);
var hasManyLoaded = hasMany ? hasMany.filter(function(item) {
  return !item.record.get('currentState.isEmpty');
}) : [];
```

**Comment by wvteijlingen** [comment]
Yes, this has changed in Ember Data beta17 I believe. I had to update this as well to get it working in beta 18.

**Comment by green-arrow** [comment]
This is fixed in #84

**Comment by jonkoops** [comment]
It seems this issue was solved by @Asgaroth in [his pull request](https://github.com/kurko/ember-json-api/pull/80). The specific LOC can be found [here](https://github.com/kurko/ember-json-api/blob/master/src/json-api-adapter.js#L118). @green-arrow I'm closing this issue and the associated pull request. If I missed anything let me know.

**Comment by green-arrow** [comment]
@jonkoops Is it possible to get a new release of this cut?I believe this will prevent people from being able to update ember-data.

**Comment by jonkoops** [comment]
@kurko Could you tag a new release? I am not familiar with the process. Or can I just add a git tag?

**Comment by kurko** [comment]
@green-arrow @jonkoops so, I pushed `0.5.0` tag to Github.

As for the NPM release, it's really odd. I had released this weak. I guess I either forgot to do the final `<enter>` to execute the command or there some cache in the interwebz. Anyway, it's there! https://www.npmjs.com/package/ember-json-api

**Comment by jonkoops** [comment]
Nice. Thanks @kurko
